### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by djks74** [wenzhiming/flutter_webview_pro#1]
Hi,
This is great!

but can you fix the language in english when prompting file chooser?

Thanks alot for this plugin.

btw,
could you add geolocation support with this plugin?

**Comment by pocrone** [comment]
Yeah , i do face same problem that file chooser use chinese language ,

**Comment by wenzhiming** [comment]
@djks74  Hello, English is supported on version 0.7.0

**Comment by djks74** [comment]
@wenzhiming Thanks for this. :-)
