### ISSUE TITLE
IOS运行的时候回报错

### ISSUE THREAD

**Issue by zhoujia456888** [wenzhiming/flutter_webview_pro#11]
IOS运行的时候会报错，打开APP就定位到IOS文件这一行
(void)registerWithRegistrar:(NSObject)registrar {
FLTWebViewFactory webviewFactory =
[[FLTWebViewFactory alloc] initWithMessenger:registrar.messenger];
[registrar registerViewFactory:webviewFactory withId:@"plugins.flutter.io/webview"];
[FLTCookieManager registerWithRegistrar:registrar];
}

不知道是不是跟webview_flutter: 2.8.0还是flutter_webview_plugin: ^0.4.0有冲突？

**Comment by wenzhiming** [comment]
能说具体一点吗？

**Comment by zhoujia456888** [comment]
打开APP就定位到IOS文件这一行
(void)registerWithRegistrar:(NSObject)registrar {
FLTWebViewFactory webviewFactory =
[[FLTWebViewFactory alloc] initWithMessenger:registrar.messenger];
[registrar registerViewFactory:webviewFactory withId:@"plugins.flutter.io/webview"];
[FLTCookieManager registerWithRegistrar:registrar];
}

**Comment by zhoujia456888** [comment]
![image](https://user-images.githubusercontent.com/7905253/150761100-033c2bef-6f23-4f50-a350-a86c05c96748.png)
