### ISSUE TITLE
1.0.3版本IOS也还是报错

### ISSUE THREAD

**Issue by zhoujia456888** [wenzhiming/flutter_webview_pro#12]
我试了，不加flutter_webview_pro 1.0.3 IOS就能打开，加了就会报错，还是原来的那个错。位置是webview_flutter_wkwebview这个包,webview_flutter_wkwebview是官方[webview_flutter](https://github.com/flutter/plugins/tree/master/packages/webview_flutterl)下面的。
![image](https://user-images.githubusercontent.com/7905253/150912178-b448d25e-4e54-4aab-b9d2-5c91b656c2a9.png)

**Comment by wenzhiming** [comment]
你删掉ios/.symlinks目录，重新运行flutter build ios试试

**Comment by zhoujia456888** [comment]
一样，我删了ios/.symlinks、Pods、Podfile.lock、pubspec.lock，然后flutter clean、flutter pub get、pod install再打开xcode build -run，一进APP在启动界面就会卡住。我看了.symlinks下flutter_webview_pro/ios里面的代码确实是1.0.3的了，但是不知道为什么就是会卡住报错。
![image](https://user-images.githubusercontent.com/7905253/150919452-96491dc2-742e-4394-b667-83de18a9390f.png)

**Comment by wenzhiming** [comment]
我这里是删掉ios/.symlinks目录→运行flutter clean→flutter build ios→
Xcode run就可以了

**Comment by zhoujia456888** [comment]
不行，我直接新建了一个flutter项目，然后只引入了flutter_webview_pro: ^1.0.3和webview_flutter: ^2.8.0。IOS运行还是卡住报错。
我还试了下删掉ios/.symlinks目录→运行flutter clean→flutter build ios→Xcode run。结果一样
贴一下 flutter doctor -v
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/zhoujia/FlutterProject/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/zhoujia/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/zhoujia/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • ONEPLUS A3000 (mobile) • 5591fe92                             • android-arm64  • Android 9 (API 28)
    • iPhone 11 (mobile)     • 9CCB6C4A-BEE3-48BF-8D04-7EF8768AEBDA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Microsoft Edge 97.0.1072.69

• No issues found!
```

**Comment by zhoujia456888** [comment]
还是说和我用Xcode 的iphone11 模拟器运行有关系？

**Comment by bebee** [comment]
我真机测试一样的结果,也是同样的错误

**Comment by xfy6238** [comment]
遇到同样的问题, 1.0.3 , iOS  运行直接崩溃;
thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
[        ]     frame #0: 0x00000001ccd957b0 libsystem_kernel.dylib`__pthread_kill + 8
[        ] libsystem_kernel.dylib`__pthread_kill:
[        ] ->  0x1ccd957b0 <+8>:  b.lo   0x1ccd957cc               ; <+36>
[        ]     0x1ccd957b4 <+12>: stp    x29, x30, [sp, #-0x10]!
[        ]     0x1ccd957b8 <+16>: mov    x29, sp
[        ]     0x1ccd957bc <+20>: bl     0x1ccd721fc               ; cerror_nocancel
[        ] Target 0: (Runner) stopped.

**Comment by wenzhiming** [comment]
Please upgrade to the new version 3.0.1 + 2
