### ISSUE TITLE
[Suggestion] Take Photo not working in Android 11

### ISSUE THREAD

**Issue by Fauzdar1** [wenzhiming/flutter_webview_pro#15]
Hi, although, you've mentioned in the related issues and closed them that this issue has already been fixed, it's incomplete as you've not provided instructions or even mentioned in the ReadMe or Pub.dev package page that the Provider will need to be set-up in the Android manifest file. 

Hence, I had to find the solution when I saw this error in a toast returned by the `WebView`.
![image](https://user-images.githubusercontent.com/62703211/152404482-cba0db48-0d62-4009-8f14-4e45c52a8049.png)

So, this is the solution just in case anybody else faces the same issue:

First, Copy the following code in `AndroidManifest.xml` in `android/Main` under the `<application>` tag

 ```
<provider
    android:name="androidx.core.content.FileProvider"
    android:authorities="${applicationId}.fileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths" />
</provider>
```
(You can replace `${applicationId}` above to your package id ex: com.app.name in case it doesn't work)

Then, create the xml folder in res and create a file named: `provider_paths.xml` and then copy paste the code:

```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path
        name="external_files"
        path="." />
</paths>
```

After setting this up, Take photo will start working.

**Comment by wenzhiming** [comment]
Thank you for your suggestion, which has been added to the document [FAQ.md](https://github.com/wenzhiming/flutter_webview_pro/blob/master/FAQ.md) and RADEME#Gateway#FAQ
