### ISSUE TITLE
zoomEnabled and runJavascriptReturningResult option is missing

### ISSUE THREAD

**Issue by jishnutv** [wenzhiming/flutter_webview_pro#16]
The [webview_flutter](https://pub.dev/packages/webview_flutter) plugin has zoom option 'zoomEnabled' and 'runJavascriptReturningResult' for Run JavaScript in the context of the current page, and returns the result.

And I appreciate your great work you saved my day.

**Comment by wenzhiming** [comment]
Please upgrade to the new version 3.0.1 + 2
