### ISSUE TITLE
is the packages work on android 12 ?

### ISSUE THREAD

**Issue by hananeboussari** [wenzhiming/flutter_webview_pro#17]
i use your packages and its work well android 11, but on android 12 i can't access on the keyboard.

**Comment by hananeboussari** [comment]
can you help me with that ?

**Comment by hananeboussari** [comment]
@wenzhiming can you help with that please ?

**Comment by sc-starman** [comment]
I have the same problem, would be fixed anytime soon? 
The official package doesn't have this problem though.

**Comment by hananeboussari** [comment]
hello @wenzhiming  you forget us

**Comment by wenzhiming** [comment]
Please upgrade to the new version 3.0.1 + 2
