### ISSUE TITLE
Geolocation support please

### ISSUE THREAD

**Issue by djks74** [wenzhiming/flutter_webview_pro#5]
Dear @wenzhiming, could you please add geolocation support with next update?

Thanks alot for this.

warm regards,
Sandi

**Comment by wenzhiming** [comment]
@djks74 Hello, Geolocation is supported on version [1.0.0](https://pub.flutter-io.cn/packages/flutter_webview_pro/versions/1.0.0)

**Comment by wenzhiming** [comment]
set this `geolocationEnabled: true` @djks74

**Comment by djks74** [comment]
Thanks @wenzhiming, you are the man! :-)
