### ISSUE TITLE
安裝後 ios 無法啟動

### ISSUE THREAD

**Issue by imagine10255** [wenzhiming/flutter_webview_pro#9]
Hi, 安裝該庫之後, ios 無法正常啟動 開啟時直接閃退
android 功能是正常的

**Comment by wenzhiming** [comment]
> Hi, 安裝該庫之後, ios 無法正常啟動 開啟時直接閃退 android 功能是正常的

你好 能提供具体报错信息吗？我这边自测了下是正常的  我的手机iPhone12    iOS14.2

**Comment by imagine10255** [comment]
@wenzhiming 感謝回覆, 我再把詳細一點的資訊提供出來
